all:
	g++ -L$(ACE_ROOT)/ace -Wall -std=c++11 -pthread -DTEMPLATE_HEADERS_INCLUDE_SOURCE -o ACESimpleServer ../rol_interceptor.cpp ACESimpleServer_q4.cpp -I$(ACE_ROOT) -lACE

clean:
	rm ACESimpleServer *~


